version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      azalea:
        patterns:
          - "azalea-*"
      vulkan:
        patterns:
          - "ash"
          - "ash-window"
          - "gpu-allocator"

  - package-ecosystem: cargo
    directory: /launcher/src-tauri
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /launcher
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
